# Node.js with Azure DevOps pipeline

trigger: none


pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/my-node-app.zip'
    replaceExistingArchive: true
  displayName: 'Archive files'

- script: |
    npm version patch -m "Bump version to %s [skip ci]"
    git config --global user.email "Anilkumar1529@gmail.com"  # Replace with your email
    git config --global user.name "Anilkumar1529"         # Replace with your name
    git add package.json
    git commit -m "Bump package version [skip ci]"
  displayName: 'Increment Version and Commit'

- task: npmAuthenticate@0
  inputs:
    workingFile: .npmrc                ## Path to the npmrc file
    customEndpoint: #Optional          ## Comma-separated list of npm service connection names for registries from external organizations. For registries in your org, leave this blank


- script: |
    # Publish the updated package to Azure DevOps
    npm publish --registry=https://pkgs.dev.azure.com/CloudBuildersTech/KCOverseas/_packaging/test/npm/registry/
  displayName: 'npm publish to Azure DevOps feed'

